# ------------------- Dependencies stage ------------------- #
FROM node:lts-alpine AS deps

RUN apk update && apk -i add dumb-init

WORKDIR /app

COPY package*.json .

RUN npm ci --silent
# ------------------- Dependencies stage ------------------- #

# ------------------- Builder stage ------------------- #
FROM node:lts-alpine AS builder

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules

COPY . .

ENV NODE_ENV=production

RUN npm run build
# ------------------- Builder stage ------------------- #

# ------------------- Runtime stage ------------------- #
FROM node:lts-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

# create non-root user
RUN addgroup -S app && adduser -S -G app app

# copy only what's needed
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/node_modules ./node_modules

# copy built output if present
COPY --from=builder /app/dist ./dist

USER app

CMD ["npm", "run", "start:docker"]
# ------------------- Runtime stage ------------------- #
